### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by AcidZ3r0** [john-sevsk/cynpro#1]
Hello, dear!
I can't compile this, i'm get some errors
`make
cc -I/usr/include/libusb-1.0 -Wall  -lusb-1.0  cynpro.c   -o cynpro
/tmp/ccpmsMgY.o: In function `led_color_rgb':
cynpro.c:(.text+0xe2): undefined reference to `libusb_control_transfer'
/tmp/ccpmsMgY.o: In function `led_intensity':
cynpro.c:(.text+0x263): undefined reference to `libusb_control_transfer'
/tmp/ccpmsMgY.o: In function `led_switch':
cynpro.c:(.text+0x34f): undefined reference to `libusb_control_transfer'
/tmp/ccpmsMgY.o: In function `led_breathing_color_pattern':
cynpro.c:(.text+0x433): undefined reference to `libusb_control_transfer'
/tmp/ccpmsMgY.o: In function `led_breathing':
cynpro.c:(.text+0x543): undefined reference to `libusb_control_transfer'
/tmp/ccpmsMgY.o: In function `claim_interface':
cynpro.c:(.text+0x5e1): undefined reference to `libusb_claim_interface'
cynpro.c:(.text+0x602): undefined reference to `libusb_release_interface'
/tmp/ccpmsMgY.o: In function `open_device':
cynpro.c:(.text+0x635): undefined reference to `libusb_open'
cynpro.c:(.text+0x64a): undefined reference to `libusb_set_auto_detach_kernel_driver'
cynpro.c:(.text+0x669): undefined reference to `libusb_close'
/tmp/ccpmsMgY.o: In function `inspect_device':
cynpro.c:(.text+0x6b0): undefined reference to `libusb_get_device_descriptor'
/tmp/ccpmsMgY.o: In function `walk_devices':
cynpro.c:(.text+0x71f): undefined reference to `libusb_get_device_list'
cynpro.c:(.text+0x775): undefined reference to `libusb_free_device_list'
/tmp/ccpmsMgY.o: In function `main':
cynpro.c:(.text+0xbc3): undefined reference to `libusb_init'
cynpro.c:(.text+0xbe7): undefined reference to `libusb_set_debug'
cynpro.c:(.text+0xbfe): undefined reference to `libusb_exit'
collect2: error: ld returned 1 exit status
`
I have installed libusb-1.0 and libusb-1.0-dev packages, my OS Ubuntu Linux 16.04.

**Comment by john-sevsk** [comment]
I fixed Makefile. Please download and build again.

**Comment by AcidZ3r0** [comment]
Wokred. Thank You!
