### ISSUE TITLE
Support for Cynosa Chroma

### ISSUE THREAD

**Issue by amansx** [john-sevsk/cynpro#3]
Hey,
Would be awesome if you could take a look into supporting Cynosa Chroma? or point me to where you got the specs for Cynosa Pro and I can maybe help with Chroma and Chroma Pro,

Thanks a bunch!

**Comment by john-sevsk** [comment]
Hi.
I have only Cynosa Pro and I can't add support for other keyboards. You should write a program for your keyboard yourself.
What I did is I used a Windows machine (on VirtualBox) with original razer's driver.
To record traffic between a driver and a keyboard I used Microsoft Message Analyzer (https://www.microsoft.com/en-us/download/details.aspx?id=44226).
Then I used recorded traffic to write this program.
To understand Razer's protocol read sources of openrazer project (https://openrazer.github.io/)

**Comment by Zex-Lucifer** [comment]
please help me with my razer cynosa pro bundle. The alphanumeric keys wont work in some of the applications for some reason , but works when I surf the internet or when I have not opened and appication
